"""Updating metrics based on our approach to computation

Revision ID: 021aecd5023e
Revises: c3da4b874c93
Create Date: 2025-03-06 09:40:58.957653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021aecd5023e'
down_revision: Union[str, None] = 'c3da4b874c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('combined_readability_score', sa.Float(), nullable=True, comment='Combined weighted score from all readability metrics (0-100)'))
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('flesch_reading_ease', sa.Float(), nullable=True, comment='Flesch Reading Ease score (0-100)'))
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('smog_index_score', sa.Float(), nullable=True, comment='SMOG Index score normalized to 0-100'))
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('automated_readability_score', sa.Float(), nullable=True, comment='Automated Readability Index normalized to 0-100'))
    op.drop_column('agency_regulation_document_historical_metrics', 'readability_score')
    op.drop_column('agency_regulation_document_historical_metrics', 'language_complexity_score')
    op.drop_column('agency_regulation_document_historical_metrics', 'average_word_length')
    op.drop_column('agency_regulation_document_historical_metrics', 'average_sentence_length')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('average_sentence_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('average_word_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('language_complexity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('readability_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('agency_regulation_document_historical_metrics', 'automated_readability_score')
    op.drop_column('agency_regulation_document_historical_metrics', 'smog_index_score')
    op.drop_column('agency_regulation_document_historical_metrics', 'flesch_reading_ease')
    op.drop_column('agency_regulation_document_historical_metrics', 'combined_readability_score')
    # ### end Alembic commands ###
