"""Remove content snapshot

Revision ID: 0486cd13e285
Revises: dda9905c6f0f
Create Date: 2025-03-06 15:06:35.446176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0486cd13e285'
down_revision: Union[str, None] = 'dda9905c6f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency_regulation_document_historical_metrics', 'content_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_regulation_document_historical_metrics', sa.Column('content_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
