"""Create agency document counts

Revision ID: 3e1c58d4dff4
Revises: 567aa2c2e029
Create Date: 2025-03-04 20:08:16.418733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1c58d4dff4'
down_revision: Union[str, None] = '567aa2c2e029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_document_counts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('query_date', sa.Date(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('per_page', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agency_document_counts')
    # ### end Alembic commands ###
