"""Add metrics model

Revision ID: ad922f26625a
Revises: c7d68490dd16
Create Date: 2025-03-05 13:10:29.897248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad922f26625a'
down_revision: Union[str, None] = 'c7d68490dd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('agency_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_documents_document_id'), 'agency_documents', ['document_id'], unique=False)
    op.create_table('agency_regulation_document_historical_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metrics_date', sa.Date(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('paragraph_count', sa.Integer(), nullable=False),
    sa.Column('sentence_count', sa.Integer(), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=True),
    sa.Column('subpart_count', sa.Integer(), nullable=True),
    sa.Column('language_complexity_score', sa.Float(), nullable=True),
    sa.Column('readability_score', sa.Float(), nullable=True),
    sa.Column('average_sentence_length', sa.Float(), nullable=True),
    sa.Column('average_word_length', sa.Float(), nullable=True),
    sa.Column('total_authors', sa.Integer(), nullable=True),
    sa.Column('revision_authors', sa.Integer(), nullable=True),
    sa.Column('simplicity_score', sa.Float(), nullable=True),
    sa.Column('content_snapshot', sa.Text(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['agency_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'metrics_date', name='uix_document_date')
    )
    op.create_index(op.f('ix_agency_regulation_document_historical_metrics_metrics_date'), 'agency_regulation_document_historical_metrics', ['metrics_date'], unique=False)
    op.add_column('agencies', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('agencies_slug_key', 'agencies', type_='unique')
    op.create_index(op.f('ix_agencies_slug'), 'agencies', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agencies_slug'), table_name='agencies')
    op.create_unique_constraint('agencies_slug_key', 'agencies', ['slug'])
    op.drop_column('agencies', 'description')
    op.drop_index(op.f('ix_agency_regulation_document_historical_metrics_metrics_date'), table_name='agency_regulation_document_historical_metrics')
    op.drop_table('agency_regulation_document_historical_metrics')
    op.drop_index(op.f('ix_agency_documents_document_id'), table_name='agency_documents')
    op.drop_table('agency_documents')
    # ### end Alembic commands ###
