"""Add target year

Revision ID: c3da4b874c93
Revises: ad922f26625a
Create Date: 2025-03-05 17:09:05.518225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3da4b874c93'
down_revision: Union[str, None] = 'ad922f26625a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_document_counts', sa.Column('target_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency_document_counts', 'target_year')
    # ### end Alembic commands ###
