"""Add processing_status to search descriptors

Revision ID: c7d68490dd16
Revises: 3e1c58d4dff4
Create Date: 2025-03-04 20:46:19.075793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d68490dd16'
down_revision: Union[str, None] = '3e1c58d4dff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency_title_search_descriptors', sa.Column('processing_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency_title_search_descriptors', 'processing_status')
    # ### end Alembic commands ###
