"""Add a agency_id where its missing

Revision ID: dda9905c6f0f
Revises: 021aecd5023e
Create Date: 2025-03-06 10:00:09.055857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda9905c6f0f'
down_revision: Union[str, None] = '021aecd5023e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agency_documents', 'agency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agency_documents', 'agency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
